# Generated by Django 5.1 on 2024-11-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancestatus_galerydiscipline_galeryfront_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainuser',
            table='Main_user',
        ),
    ]
