# Generated by Django 5.1 on 2024-11-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mainuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
    ]
