# Generated by Django 5.1 on 2024-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Main_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(max_length=20)),
                ('attendance_date', models.DateField()),
                ('attendace_comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=50)),
                ('coach_img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=50)),
                ('discipline_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EliteAthlete',
            fields=[
                ('elite_athlete_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('elite_athlete_name', models.CharField(max_length=100)),
                ('elite_athlete_headquarters', models.CharField(blank=True, max_length=50, null=True)),
                ('elite_athlete_descipline', models.CharField(max_length=30)),
                ('elite_athlete_description', models.CharField(max_length=100)),
                ('elite_athlete_img', models.BinaryField(blank=True, null=True)),
                ('elite_athlete_career', models.CharField(max_length=30)),
                ('player_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'elite_athlete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('events_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('events_name', models.CharField(max_length=50)),
                ('events_status', models.CharField(max_length=50)),
                ('events_start', models.DateField()),
                ('events_end', models.DateField()),
                ('events_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('galery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('galery_img', models.BinaryField()),
                ('galery_status', models.CharField(max_length=50)),
                ('galery_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'galery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePosition',
            fields=[
                ('game_position_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_position_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'game_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('news_name', models.CharField(max_length=50)),
                ('news_status', models.CharField(max_length=50)),
                ('news_description', models.CharField(blank=True, max_length=500, null=True)),
                ('news_date', models.DateField()),
                ('news_img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_rut', models.CharField(max_length=13)),
                ('player_name', models.CharField(max_length=50)),
                ('player_last_name', models.CharField(max_length=50)),
                ('player_headquarters', models.CharField(blank=True, max_length=50, null=True)),
                ('player_career', models.CharField(max_length=30)),
                ('player_img', models.BinaryField(blank=True, null=True)),
                ('player_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('statistic_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'statistic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('team_roster_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_roster_date', models.DateField()),
            ],
            options={
                'db_table': 'team_roster',
                'managed': False,
            },
        ),
    ]
