# Generated by Django 5.1 on 2024-11-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241009_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=20)),
                ('status_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'attendance_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaleryDiscipline',
            fields=[
                ('galery_dis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('galery_dis_img', models.BinaryField()),
                ('galery_dis_status', models.FloatField()),
                ('galery_dis_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('galery_dis_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'galery_discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaleryFront',
            fields=[
                ('galery_front_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('galery_front_img', models.BinaryField()),
                ('galery_front_status', models.FloatField()),
                ('galery_front_title', models.CharField(blank=True, max_length=100, null=True)),
                ('galery_front_description', models.CharField(blank=True, max_length=200, null=True)),
                ('galery_front_place', models.CharField(blank=True, max_length=200, null=True)),
                ('galery_front_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'galery_front',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GaleryGeneral',
            fields=[
                ('galery_gen_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('galery_gen_img', models.BinaryField()),
                ('galery_gen_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('galery_gen_status', models.FloatField()),
                ('galery_gen_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'galery_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=100)),
                ('player_rut', models.CharField(max_length=13)),
                ('player_name', models.CharField(max_length=50)),
                ('player_last_name', models.CharField(max_length=50)),
                ('discipline_name', models.CharField(max_length=50)),
                ('player_headquarters', models.CharField(blank=True, max_length=50, null=True)),
                ('player_career', models.CharField(max_length=30)),
                ('request_status', models.CharField(max_length=30)),
                ('request_date', models.DateField()),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('status_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='EliteAthlete',
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='GamePosition',
        ),
        migrations.AlterModelTable(
            name='mainuser',
            table='main_user',
        ),
    ]
